name: flutter_markdown
description: A Markdown renderer for Flutter.
homepage: https://github.com/flutter/flutter_markdown
version: 0.3.2

dependencies:
  flutter:
    sdk: flutter
  markdown: ^4.0.1
  meta: ^1.7.0
  path: ^1.8.0
  url_launcher: ^6.0.17
  shared_preferences: ^2.0.11


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^3.0.0


environment:
  sdk: '>=2.5.0 <3.0.0'
  flutter: '>=1.10.7 <2.0.0'

flutter:
  assets:
    - assets/logo.png
