name: flutter_markdown
description: A Markdown renderer for Flutter.
homepage: https://github.com/flutter/flutter_markdown
version: 0.3.2

dependencies:
  flutter:
    sdk: flutter
  markdown: ^7.2.2
  meta: ^1.15.0
  path: ^1.9.1
  url_launcher: ^6.3.1
  shared_preferences: ^2.3.2


environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0 <4.0.0'

flutter:
  assets:
    - assets/logo.png
